### ISSUE TITLE
TODO things

### ISSUE THREAD

**Issue by Antolin1** [Antolin1/code-inter-dataset-duplication#1]
- [x] code search: add evaluation after each epoch and implement early stopping (easy).
- [ ] check bleu. The results are lower than the reported in papers (idk if pre-processing or bleu)
- [x] check where lora is acting (easy and almost done)
- [x] make prefix work (easy)
- [ ] check if bias definition is reasonable and consider three control models
- [ ] the rand model does not work for codesearch. It does not converge
- [ ] check RQs
- [ ] check strategies to freeze layers in seq2seq models
- [ ] write final experiment scripts
- [ ] run all the experiments
